version: "3"

services:
  vue:
    build: ./
    volumes:
      - ./:/www
    ports:
      - "127.0.0.1:8901:8080"
    tty: true

  web:
    build: web
    ports:
      - "127.0.0.1:3031:3031"
    environment:
      TZ: "Asia/Tokyo"
      CK: ${CK:-notset}
      CS: ${CS:-notset}
      AT: ${AT:-notset}
      AS: ${AS:-notset}
      SESSION_SECRET: ${SESSION_SECRET:-notset}
    volumes:
      - ./web:/var/www/
    stdin_open: true

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - web
    ports:
      - "${NGINX_PORT:-8888}:80"
    environment:
      TZ: "Asia/Tokyo"
